[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --alluredir=reports/allure-results --clean-alluredir --reruns=2 --reruns-delay=5
markers =
    slow: marks tests as slow
    unit: 单元接口测试
    integration: 集成接口测试
    scenario: 业务场景测试
